FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build_env
WORKDIR /app
COPY ["aspnet/aspnet.csproj", "aspnet/"]
RUN dotnet restore "aspnet/aspnet.csproj"
COPY . .
RUN  dotnet tool install --global dotnet-ef --version 7.0.0

